language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '12'
before_script:
  - npm prune
script:
  - npm test
  - ./test/test.sh
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
